version: '3.8'

services:
  app:
    build: ../seta-service
    ports:
      - "8080:8080"
    volumes:
      - ../seta-service/logs:/app/logs
    environment:
      - DATABASE_URL=postgres://seta_user:seta_password@db:5432/seta_db?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=seta_user
      - POSTGRES_PASSWORD=seta_password
      - POSTGRES_DB=seta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: "10001:10001" # Run as the loki user

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ../seta-service/logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

volumes:
  loki-data:
  postgres_data: